[package]
name    = "localsend-cli"
version = "1.0.2"
edition = "2024"

[dependencies]
infer = { version = "0.22.0", default-features = false, features = ["std"] }
mime_guess = { version = "2.0.5", default-features = false }
miniserde = { version = "0.1.45", default-features = false, features = ["std"] }
rs-machineid = "0.2.0"
rune-sha256 = "0.1.1"
smol = "2.0.2"
smol-timeout = "0.6.1"
thiserror_lite = "0.1.0"
tiny_http = "0.12.0"
zfish = { version = "0.1.10", default-features = false, features = [
  "interactive",
  "progress",
] }

[profile.release]
codegen-units = 1
lto           = true
opt-level     = "s"
panic         = "abort"
strip         = true
